name: digivice_virtual_bridge
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.5.0
  webview_flutter: ^4.0.0
  path_provider: ^2.0.15
  android_intent_plus: ^5.2.1
  flutter_nfc_hce: ^0.1.8
  # flutter_in_app_pip: ^1.7.4
  flutter_overlay_window: ^0.4.5
  flutter_custom_hce:
    path: ../../flutter_custom_hce

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  # uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
