export const CLEANING_HIGHLIGHT_Z_INDEX_BASE = 1_000_100;
export const CLEANING_DIM_OVERLAY_Z_INDEX = CLEANING_HIGHLIGHT_Z_INDEX_BASE;
export const NON_FOCUSED_TARGET_Z_INDEX =
  CLEANING_HIGHLIGHT_Z_INDEX_BASE + 1;
export const NON_FOCUSED_BORDER_Z_INDEX = CLEANING_HIGHLIGHT_Z_INDEX_BASE + 2;
export const FOCUSED_TARGET_Z_INDEX = CLEANING_HIGHLIGHT_Z_INDEX_BASE + 3;
export const FOCUSED_BORDER_Z_INDEX = CLEANING_HIGHLIGHT_Z_INDEX_BASE + 4;
export const BROOM_Z_INDEX = CLEANING_HIGHLIGHT_Z_INDEX_BASE + 5;

export function getCleaningTargetZIndex(isFocused: boolean): number {
  return isFocused ? FOCUSED_TARGET_Z_INDEX : NON_FOCUSED_TARGET_Z_INDEX;
}
